// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mygaskulwoslmqxrgoxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15Z2Fza3Vsd29zbG1xeHJnb3h2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMDMxMDksImV4cCI6MjA3Mzg3OTEwOX0.2uFOZDgyA7V0xoknHoUue3i7QEYmoCYYidqM0TcSu_4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});